export const dishes = [
  {
    type: "Desayuno",
    name: "Chilaquiles",
    description: "Chilaquiles con bisteck, pollo o huevo",
    price: 89,
    available: true,
    permanet: true,
    weekly: true,
    daily: false,
  },
  {
    type: "Desayuno",
    name: "Huevos la tia",
    description: "Huevos preparados de cierta forma",
    price: 89,
    available: true,
    permanet: true,
    weekly: true,
    daily: false,
  },
  {
    type: "Desayuno",
    name: "Molletes",
    description: "Huevos preparados de cierta forma",
    price: 89,
    available: true,
    permanet: true,
    weekly: true,
    daily: false,
  },
  {
    type: "Desayuno",
    name: "Huevos al gusto",
    description: "Huevos preparados de cierta forma",
    price: 89,
    available: true,
    permanet: true,
    weekly: true,
    daily: false,
  },
  {
    type: "Comida",
    name: "Pollo en mole verde",
    description: "Pollo en mole verde acompañado de frijoles",
    price: 92,
    available: true,
    permanet: false,
    weekly: true,
    daily: false,
  },
  {
    type: "Comida",
    name: "Enchilada Suizas",
    description: "Pollo en mole verde acompañado de frijoles",
    price: 92,
    available: true,
    permanet: false,
    weekly: false,
    daily: true,
  },
  {
    type: "Cena",
    name: "Enchilada Suizas",
    description: "Pollo en mole verde acompañado de frijoles",
    price: 92,
    available: true,
    permanet: false,
    weekly: false,
    daily: true,
  },
  {
    type: "Bebida",
    name: "Agua de Horchata",
    description: "",
    price: 20,
    available: true,
    permanet: true,
    weekly: false,
    daily: true,
  },
  {
    type: "Postre",
    name: "Enchilada Suizas",
    description: "Pollo en mole verde acompañado de frijoles",
    price: 92,
    available: true,
    permanet: false,
    weekly: false,
    daily: true,
  },
  {
    type: "Antojo",
    name: "Enchilada Suizas",
    description: "Pollo en mole verde acompañado de frijoles",
    price: 92,
    available: true,
    permanet: false,
    weekly: false,
    daily: true,
  },
];
